-- 자산 시드: 미국/한국 주요 종목 + ETF

insert into public.assets (ticker, yahoo_symbol, name, market, type, sector, asset_class, current_risk_level, impact_hint) values
-- US STOCK
('AAPL', 'AAPL', '애플',         'US', 'STOCK', 'INFORMATION_TECHNOLOGY',   'STOCK', 3, '아이폰을 만든 그 회사'),
('MSFT', 'MSFT', '마이크로소프트', 'US', 'STOCK', 'INFORMATION_TECHNOLOGY',   'STOCK', 2, '윈도우와 클라우드의 강자'),
('GOOGL','GOOGL','알파벳',        'US', 'STOCK', 'COMMUNICATION_SERVICES',   'STOCK', 3, '구글의 모회사'),
('AMZN', 'AMZN', '아마존',        'US', 'STOCK', 'CONSUMER_DISCRETIONARY',   'STOCK', 3, '세계 최대 이커머스'),
('TSLA', 'TSLA', '테슬라',        'US', 'STOCK', 'CONSUMER_DISCRETIONARY',   'STOCK', 5, '전기차의 대표주자'),
('NVDA', 'NVDA', '엔비디아',      'US', 'STOCK', 'INFORMATION_TECHNOLOGY',   'STOCK', 5, 'AI 반도체의 왕'),
('META', 'META', '메타',          'US', 'STOCK', 'COMMUNICATION_SERVICES',   'STOCK', 4, '페이스북·인스타그램 운영사'),
('JPM',  'JPM',  'JP모건체이스',  'US', 'STOCK', 'FINANCIALS',               'STOCK', 2, '미국 최대 은행'),
('JNJ',  'JNJ',  '존슨앤드존슨',  'US', 'STOCK', 'HEALTH_CARE',              'STOCK', 1, '헬스케어 대표 기업'),
('V',    'V',    '비자',          'US', 'STOCK', 'FINANCIALS',               'STOCK', 2, '글로벌 결제 네트워크'),
('WMT',  'WMT',  '월마트',        'US', 'STOCK', 'CONSUMER_STAPLES',         'STOCK', 1, '미국 최대 유통기업'),
('PG',   'PG',   '프록터앤드갬블','US', 'STOCK', 'CONSUMER_STAPLES',         'STOCK', 1, '생활용품의 거인'),
('KO',   'KO',   '코카콜라',      'US', 'STOCK', 'CONSUMER_STAPLES',         'STOCK', 1, '음료 시장의 아이콘'),
('DIS',  'DIS',  '디즈니',        'US', 'STOCK', 'COMMUNICATION_SERVICES',   'STOCK', 3, '엔터테인먼트 제국'),
('NFLX', 'NFLX', '넷플릭스',      'US', 'STOCK', 'COMMUNICATION_SERVICES',   'STOCK', 4, '글로벌 OTT 1위'),
('XOM',  'XOM',  '엑슨모빌',      'US', 'STOCK', 'ENERGY',                   'STOCK', 3, '미국 최대 석유 기업'),
('CVX',  'CVX',  '셰브론',        'US', 'STOCK', 'ENERGY',                   'STOCK', 2, '글로벌 에너지 메이저'),
('BA',   'BA',   '보잉',          'US', 'STOCK', 'INDUSTRIALS',              'STOCK', 4, '항공기 제조의 양대 축'),
('CAT',  'CAT',  '캐터필러',      'US', 'STOCK', 'INDUSTRIALS',              'STOCK', 3, '중장비의 대명사'),
('AMT',  'AMT',  '아메리칸타워',  'US', 'STOCK', 'REAL_ESTATE',              'STOCK', 2, '글로벌 통신 인프라 리츠'),
('NEE',  'NEE',  '넥스트에라에너지','US','STOCK', 'UTILITIES',                'STOCK', 2, '미국 최대 신재생 유틸리티'),
('LIN',  'LIN',  '린데',          'US', 'STOCK', 'MATERIALS',                'STOCK', 2, '산업용 가스 글로벌 리더'),
-- US ETF
('VOO',  'VOO',  'Vanguard S&P 500 ETF', 'US', 'ETF', null, 'ETF', 2, '미국 대형주 500개 추종'),
('QQQ',  'QQQ',  'Invesco QQQ Trust',    'US', 'ETF', null, 'ETF', 3, '나스닥 100 추종'),
('SPY',  'SPY',  'SPDR S&P 500 ETF',     'US', 'ETF', null, 'ETF', 2, '가장 오래된 S&P 500 ETF'),
-- KR STOCK (KS = KOSPI, KQ = KOSDAQ)
('005930','005930.KS','삼성전자',           'KR', 'STOCK', 'INFORMATION_TECHNOLOGY',  'STOCK', 2, '한국 시가총액 1위'),
('000660','000660.KS','SK하이닉스',         'KR', 'STOCK', 'INFORMATION_TECHNOLOGY',  'STOCK', 4, '메모리 반도체 강자'),
('035420','035420.KS','네이버',             'KR', 'STOCK', 'COMMUNICATION_SERVICES',  'STOCK', 3, '국내 최대 검색 포털'),
('035720','035720.KS','카카오',             'KR', 'STOCK', 'COMMUNICATION_SERVICES',  'STOCK', 4, '국민 메신저 운영사'),
('207940','207940.KS','삼성바이오로직스',   'KR', 'STOCK', 'HEALTH_CARE',             'STOCK', 3, '국내 최대 바이오 CMO'),
('005380','005380.KS','현대차',             'KR', 'STOCK', 'CONSUMER_DISCRETIONARY',  'STOCK', 3, '한국 대표 완성차'),
('000270','000270.KS','기아',               'KR', 'STOCK', 'CONSUMER_DISCRETIONARY',  'STOCK', 3, '글로벌 완성차 브랜드'),
('051910','051910.KS','LG화학',             'KR', 'STOCK', 'MATERIALS',               'STOCK', 3, '배터리·석화 종합기업'),
('006400','006400.KS','삼성SDI',            'KR', 'STOCK', 'INFORMATION_TECHNOLOGY',  'STOCK', 4, '2차전지 글로벌 톱'),
('373220','373220.KS','LG에너지솔루션',     'KR', 'STOCK', 'INDUSTRIALS',             'STOCK', 4, '글로벌 1위 배터리 제조사'),
('068270','068270.KS','셀트리온',           'KR', 'STOCK', 'HEALTH_CARE',             'STOCK', 4, '바이오시밀러의 강자'),
('105560','105560.KS','KB금융',             'KR', 'STOCK', 'FINANCIALS',              'STOCK', 2, '국내 1위 금융지주'),
('055550','055550.KS','신한지주',           'KR', 'STOCK', 'FINANCIALS',              'STOCK', 2, '4대 금융지주 중 하나'),
('086790','086790.KS','하나금융지주',       'KR', 'STOCK', 'FINANCIALS',              'STOCK', 2, '하나은행 모회사'),
('028260','028260.KS','삼성물산',           'KR', 'STOCK', 'INDUSTRIALS',             'STOCK', 2, '삼성 그룹 지주격'),
('066570','066570.KS','LG전자',             'KR', 'STOCK', 'CONSUMER_DISCRETIONARY',  'STOCK', 3, '글로벌 가전 강자'),
('003550','003550.KS','LG',                 'KR', 'STOCK', 'INDUSTRIALS',             'STOCK', 2, 'LG그룹 지주회사'),
('015760','015760.KS','한국전력',           'KR', 'STOCK', 'UTILITIES',               'STOCK', 2, '국내 유일 전력 공기업'),
('017670','017670.KS','SK텔레콤',           'KR', 'STOCK', 'COMMUNICATION_SERVICES',  'STOCK', 1, '국내 1위 이동통신'),
('030200','030200.KS','KT',                 'KR', 'STOCK', 'COMMUNICATION_SERVICES',  'STOCK', 1, '유무선 통신 사업자'),
('034730','034730.KS','SK',                 'KR', 'STOCK', 'INDUSTRIALS',             'STOCK', 2, 'SK그룹 지주회사'),
('096770','096770.KS','SK이노베이션',       'KR', 'STOCK', 'ENERGY',                  'STOCK', 3, '정유·배터리 사업'),
('251270','251270.KS','넷마블',             'KR', 'STOCK', 'COMMUNICATION_SERVICES',  'STOCK', 4, '국내 대형 게임사'),
-- KR ETF
('069500','069500.KS','KODEX 200',                  'KR', 'ETF', null, 'ETF', 2, '코스피 200 추종 ETF'),
('360750','360750.KS','TIGER 미국S&P500',           'KR', 'ETF', null, 'ETF', 2, '원화로 사는 S&P 500'),
('091160','091160.KS','KODEX 반도체',               'KR', 'ETF', null, 'ETF', 4, '국내 반도체주 묶음'),
('305080','305080.KS','TIGER 미국나스닥100',        'KR', 'ETF', null, 'ETF', 3, '원화 나스닥100 ETF'),
('114800','114800.KS','KODEX 인버스',               'KR', 'ETF', null, 'ETF', 5, '코스피 200 역추종 ETF');
